"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let places = [`ghaza`, `makkah`, `maddina`, `palastine`, `quetta`];
console.log(`origional: ` + places);
console.log(`copy:` + [...places].sort());
console.log(`origional: ` + places);
console.log(`copy:` + [...places].sort().reverse());
console.log(`origional: ` + places);
console.log(`copy:` + [...places].sort().reverse());
console.log(`copy:` + [...places].sort());
console.log(`copy:` + [...places].sort().reverse());
